\input texinfo  @c -*-Texinfo-*-
@setfilename xslt-process.info
@settitle XSLT-process minor mode

@include version.texi

@ifinfo
@dircategory Miscellaneous
@direntry
* XSLT-process::                  XSLT processing and debugging within Emacs.
@end direntry

This file documents the features of the XSLT-process minor mode.

Copyright (C) 2000--2001 Ovidiu Predescu
All rights reserved.

Distributed under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 2 of the
License, or (at your option) any later version.

@sp 2

The XSLT-process minor mode manual may be reproduced and distributed in
whole or in part, in any medium, physical or electronic, so long as this
copyright notice remains intact and unchanged on all copies.
@end ifinfo

@titlepage
@title XSLT-process minor mode
@subtitle for version @value{version}
@subtitle @value{update-month}
@author by Ovidiu Predescu
@page
@vskip 0pt plus 1filll
Copyright @copyright{} 2000, 2001 Ovidiu Predescu.
@par All rights reserved.

@sp 1

Distributed under the terms of the
@uref{http://www.gnu.org/copyleft/gpl.html, GNU General Public License}
as published by the @uref{http://www.fsf.org/, Free Software
Foundation}; either version 2 of the License, or (at your option) any
later version.

@sp 1

The @emph{XSLT-process} minor mode manual may be reproduced and
distributed in whole or in part, in any medium, physical or electronic,
so long as this copyright notice remains intact and unchanged on all
copies.
@end titlepage

@node top, What is it?, (dir), (dir)
@comment  node-name,  next,  previous,  up

@menu
* What is it?::                 
* Installation and setup::      

@detailmenu
 --- The Detailed Node Listing ---

Installation and setup

* Package installation under XEmacs::  
* Generic installation::        
* Setting up XSLT-process::     

Generic installation

* Installing Speedbar::         
* Installing XSLT-process::     

@end detailmenu
@end menu

@ifinfo
This document describes XSLT-process, a minor mode for XEmacs/GNU Emacs
that enables it for XSLT processing and debugging.
@end ifinfo



@c =========================================================================
@node What is it?, Installation and setup, top, top
@comment  node-name,  next,  previous,  up
@chapter What is it?

@emph{XSLT-process} is a minor mode for XEmacs or GNU Emacs which
transforms it into a powerful XML editor with XSLT processing and
debugging capabilities.

You can invoke an XSLT processor of choice on the current XML file
you're editing, and see the results in another buffer. In case of
errors, the error messages generated by the XSLT processor, are shown in
a compilation buffer, which allows you to quickly go to the location of
the error.

You can also run the XSLT processor in debugging mode, and view step by
step what the XSLT processor is doing. You can view the current stack
frame in the XSLT program, the current XML context node being processed,
what are the local and global variables, set breakpoints in both the XML
source file and the XSLT program.

@html
<a href="http://sourceforge.net/projects/xslt-process/"> <img
src="sflogo.png" width="88" height="31" border="0" alt="SourceForge
Logo"></a>
@end html

The author of the @emph{XSLT-process} package is
@uref{http://www.geocities.com/SiliconValley/Monitor/7464, Ovidiu
Predescu}, and the package is distributed under the terms of
@uref{http://www.gnu.org/copyleft/gpl.html, GNU General Public
License}. The project is graciously hosted by SourceForge, and could be
found at @uref{http://sourceforge.net/projects/xslt-process/,
http://sourceforge.net/projects/xslt-process/}. The current version is
@value{version}.

@c =========================================================================
@node Installation and setup,  , What is it?, top
@comment  node-name,  next,  previous,  up
@chapter Installation and setup

The @emph{XSLT-process} mode is part of XEmacs, but it works with both
XEmacs and GNU Emacs. The installation differs slighly between the two
editors as we will see shortly.

@menu
* Package installation under XEmacs::  
* Generic installation::        
* Setting up XSLT-process::     
@end menu

@c =========================================================================
@node Package installation under XEmacs, Generic installation, Installation and setup, Installation and setup
@comment  node-name,  next,  previous,  up
@section Package installation under XEmacs

@emph{XSLT-process} is also released as an XEmacs package, so if you're
an XEmacs user, chances are that the package is already installed with
your XEmacs installation. If it's not installed, try obtaining the
latest XEmacs package from your XEmacs local mirror or from the main
XEmacs ftp site. It may happen that the XEmacs package is a little older
than the currently released version of @emph{XSLT-process}, in which
case you want to follow the steps described below.

You can retrieve the XEmacs package either manually from the ftp site,
or by using the ``Options'' @result{} ``Manage packages''
menu. Follow the instructions described under the ``Options''
@result{} ``Manage packages'' @result{} ``Help'' menu entry if
you're not familiar with this procedure.

@c =========================================================================
@node Generic installation, Setting up XSLT-process, Package installation under XEmacs, Installation and setup
@comment  node-name,  next,  previous,  up
@section Generic installation

This section describes how to install @emph{XSLT-process} on your Emacs
editor, assuming either it is not already installed, or you want to
install a new version.

@menu
* Installing Speedbar::         
* Installing XSLT-process::     
@end menu

@c =========================================================================
@node  Installing Speedbar, Installing XSLT-process, Generic installation, Generic installation
@comment  node-name,  next,  previous,  up
@subsection Installing Speedbar

@emph{XSLT-process} depends on another package, @emph{Speedbar}, for
displaying breakpoints, stack frames and global and local variables. You
need to obtain and install this package first, in case you don't have it
already installed.

To verify if you have this package installed, type @kbd{M-x
speedbar-version}; this will give either an error, if the package is not
installed, or the version number of the @emph{speedbar} package if it's
already installed. You should have at least version 0.13 for
@emph{XSLT-process} to work.

In case you don't have the @emph{speedbar} package, you can obtain it
from its Web site at @uref{http://cedet.sourceforge.net/speedbar.shtml,
http://cedet.sourceforge.net/speedbar.shtml}. Unpack the package in your
@kbd{~/emacs} directory. If you don't have a @kbd{~/emacs} directory,
create one now. Then go to the speedbar directory and run

@example
$ make
@end example

If you're using XEmacs, you need to run:

@example
$ make EMACS=xemacs
@end example

This step byte-compiles all the Lisp files in the @emph{speedbar}
package using your Emacs editor. Please follow Speedbar's installation
document for more up-to-date information on how to compile it.

@c =========================================================================
@node  Installing XSLT-process,  , Installing Speedbar, Generic installation
@comment  node-name,  next,  previous,  up
@subsection Installing @emph{XSLT-process}

To install the @emph{XSLT-process} mode, first obtain the latest stable
version from the SourceForge Web site, at
@uref{http://sourceforge.net/projects/xslt-process/,
http://sourceforge.net/projects/xslt-process/}. Unpack the distribution
in your @kbd{~/emacs} directory; this will create the
@kbd{xslt-process-@value{version}} directory in your @kbd{~/emacs}
directory.

You now need to tell Emacs to look for the new package in this newly
created directory. You do this by adding the following lines in the
Emacs configuration file @kbd{~/.emacs} (if you don't have such a file,
create one now):

@example
(mapc (lambda (x)
        (pushnew (expand-file-name x) load-path))
      (list "~/emacs"
            "~/emacs/xslt-process-@value{version}/lisp"
            "~/emacs/speedbar-0.13"))
@end example

You can remove the reference to @kbd{speedbar-0.13} in the lines above,
if you didn't have to install @emph{speedbar} as described in the
previous section (@pxref{Installing Speedbar}).

@c =========================================================================
@node  Setting up XSLT-process,  , Generic installation, Installation and setup
@comment  node-name,  next,  previous,  up
@section Setting up the @emph{XSLT-process} mode

@cindex PSGML
@cindex sgml-mode.el
@cindex xslide
@emph{XSLT-process} is an Emacs minor mode, which means is extending the
functionality of whatever mode you use for editing XML or XSLT files,
instead of creating a similar one.

@emph{XSLT-process} does not try to help in the editing of XML or XSLT
files, it just enables Emacs to process such files. Thus
@emph{XSLT-process} should work with any XML/XSLT editing mode your
Emacs is configured for.

@emph{XSLT-process} was tested with both Lennart Staflin's
@uref{http://sourceforge.net/projects/psgml,PSGML} and James Clark's
@emph{sgml-mode.el} major modes for editing XML files. It also works
with Tony Graham's @uref{http://sourceforge.net/projects/xslide,xslide}
major mode for editing XSLT files.

To automatically enable the @emph{XSLT-process} minor mode for the above
major modes, add the following lines in your @kbd{~/.emacs} file:

@example
(autoload 'xslt-process-mode "xslt-process" "Emacs XSLT processing" t)
(add-hook 'sgml-mode-hook 'xslt-process-mode)
(add-hook 'xml-mode-hook 'xslt-process-mode)
(add-hook 'xsl-mode-hook 'xslt-process-mode)
@end example

You can also manually switch to this minor mode by typing @kbd{M-x
xslt-process-mode}.

You can check the modeline to see whether Emacs is in the
@emph{XSLT-process} mode. Look for the ``XSLT'' indicator in the
modeline:

@image{xslt-process-mode}

@contents

@bye
